apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deploydash-backend-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: api-deploydash.nstsdc.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: deploydash-backend
            port:
              number: 80
